# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: turn_detection.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'turn_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14turn_detection.proto\x12\rturn_detector\"-\n\x0bTurnRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\"C\n\x0cTurnResponse\x12\r\n\x05state\x18\x01 \x01(\t\x12\x12\n\nlatency_ms\x18\x02 \x01(\x04\x12\x10\n\x08model_id\x18\x03 \x01(\t\"\x0f\n\rHealthRequest\"P\n\x0eHealthResponse\x12\x0f\n\x07healthy\x18\x01 \x01(\x08\x12\x15\n\rloaded_models\x18\x02 \x03(\t\x12\x16\n\x0eserver_version\x18\x03 \x01(\t2\x9e\x01\n\rTurnDetection\x12\x44\n\x07Predict\x12\x1a.turn_detector.TurnRequest\x1a\x1b.turn_detector.TurnResponse\"\x00\x12G\n\x06Health\x12\x1c.turn_detector.HealthRequest\x1a\x1d.turn_detector.HealthResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'turn_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TURNREQUEST']._serialized_start=39
  _globals['_TURNREQUEST']._serialized_end=84
  _globals['_TURNRESPONSE']._serialized_start=86
  _globals['_TURNRESPONSE']._serialized_end=153
  _globals['_HEALTHREQUEST']._serialized_start=155
  _globals['_HEALTHREQUEST']._serialized_end=170
  _globals['_HEALTHRESPONSE']._serialized_start=172
  _globals['_HEALTHRESPONSE']._serialized_end=252
  _globals['_TURNDETECTION']._serialized_start=255
  _globals['_TURNDETECTION']._serialized_end=413
# @@protoc_insertion_point(module_scope)
