[tool.uv.sources]
videosdk-agents = { workspace = true }
videosdk-plugins-openai = { workspace = true }
videosdk-plugins-google = { workspace = true }

[tool.uv.workspace]
members = ["videosdk-plugins/*", "videosdk-agents"]

[dependency-groups]
dev = [
    "python-dotenv>=1.0.1",
]

[tool.ruff]
line-length = 100
target-version = "py39"
exclude = [".github"]

[tool.ruff.lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4", # flake8-comprehensions
    "UP", # pyupgrade
]

[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["videosdk"]

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.pytest.ini_options]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "function"
addopts = ["--import-mode=importlib", "--ignore=examples"]

[tool.mypy]
strict = true

[tool.mypy-google.genai]
follow_imports = "normal"
follow_untyped_imports = true
